# -*- coding: utf-8 -*-
"""concatanation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14fES7eQ93-Y1eoB5w_Rm6lwGMU4ryBx-
"""

concat(
    vis=[
        'M87_2017_095_lo_fixed.ms',
        'M87_2017_096_lo_fixed.ms',
        'M87_2017_100_lo_fixed.ms',
        'M87_2017_101_lo_fixed.ms',
        'M87_2017_095_hi_fixed.ms',
        'M87_2017_096_hi_fixed.ms',
        'M87_2017_100_hi_fixed.ms',
        'M87_2017_101_hi_fixed.ms'
    ],
    concatvis='M87_combined_all.ms',
    timesort=True,
    respectname=True,
    copypointing=False
)