# -*- coding: utf-8 -*-
"""importing_uvfits.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h05zyx5Xx-So7wx3Br4-rwiKdz6ZlRSE
"""

cd ~/EHTC_FirstM87Results_Apr2019/EHTC_FirstM87Results_Apr2019_uvfits/uvfits/

importuvfits(fitsfile='SR1_M87_2017_095_lo_hops_netcal_StokesI.uvfits', vis='M87_095_lo.ms')
importuvfits(fitsfile='SR1_M87_2017_096_lo_hops_netcal_StokesI.uvfits', vis='M87_096_lo.ms')
importuvfits(fitsfile='SR1_M87_2017_100_lo_hops_netcal_StokesI.uvfits', vis='M87_100_lo.ms')
importuvfits(fitsfile='SR1_M87_2017_101_lo_hops_netcal_StokesI.uvfits', vis='M87_101_lo.ms')
importuvfits(fitsfile='SR1_M87_2017_095_hi_hops_netcal_StokesI.uvfits', vis='M87_095_hi.ms')
importuvfits(fitsfile='SR1_M87_2017_096_hi_hops_netcal_StokesI.uvfits', vis='M87_096_hi.ms')
importuvfits(fitsfile='SR1_M87_2017_100_hi_hops_netcal_StokesI.uvfits', vis='M87_100_hi.ms')
importuvfits(fitsfile='SR1_M87_2017_101_hi_hops_netcal_StokesI.uvfits', vis='M87_101_hi.ms')