# -*- coding: utf-8 -*-
"""ms_tranform.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VnGQvnEZuzV_ZelYx2Ed8GoUss5bXxI8
"""

mstransform(vis='M87_095_lo.ms', outputvis='M87_2017_095_lo_fixed.ms', datacolumn='data')
mstransform(vis='M87_096_lo.ms', outputvis='M87_2017_096_lo_fixed.ms', datacolumn='data')
mstransform(vis='M87_100_lo.ms', outputvis='M87_2017_100_lo_fixed.ms', datacolumn='data')
mstransform(vis='M87_101_lo.ms', outputvis='M87_2017_101_lo_fixed.ms', datacolumn='data')
mstransform(vis='M87_095_hi.ms', outputvis='M87_2017_095_hi_fixed.ms', datacolumn='data')
mstransform(vis='M87_096_hi.ms', outputvis='M87_2017_096_hi_fixed.ms', datacolumn='data')
mstransform(vis='M87_100_hi.ms', outputvis='M87_2017_100_hi_fixed.ms', datacolumn='data')
mstransform(vis='M87_101_hi.ms', outputvis='M87_2017_101_hi_fixed.ms', datacolumn='data')