# -*- coding: utf-8 -*-
"""plotting_ms_file.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14CPkaFsYiCKdaa82KS9LAZ4G_vfoxxyb
"""

plotms(
    vis='M87_combined_all.ms',
    xaxis='u',
    yaxis='v',
    coloraxis='field',
    avgchannel='9999',
    avgtime='9999',
    transform=False,
    showgui=True
)