# -*- coding: utf-8 -*-
"""tclean_and_exporting_fits.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AJdYQWXTKg_NOPrmLHBtuh1wgmHrxq0G
"""

tclean(
    vis='M87_combined_all.ms',
    imagename='M87_final_image',
    imsize=512,
    cell='0.25uas',
    weighting='uniform',
    niter=100000,
    threshold='0.5mJy',
    cycleniter=500,
    gain=0.1,
    deconvolver='clark',
    mask='',
    restoringbeam=['20uas', '20uas', '0deg'],  # Correct format
    interactive=False,
    usemask='user',
    savemodel='modelcolumn'
)

exportfits(
    imagename='M87_final_image.image',
    fitsimage='M87_final_image.fits',
    overwrite=True
)